import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import { cn } from "@/lib/utils";
import { Provider } from "jotai";

const ggSans = localFont({
  src: "../../public/gg-sans.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={cn(
            ggSans.className,
            "flex flex-col min-h-screen items-center justify-start bg-primary-bg"
          )}
        >
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  );
}
