import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import Header from "../components/Header";
import { cn } from "@/lib/utils";
import { Provider } from "jotai";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

const ggSans = localFont({
  src: "../../public/gg-sans.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createSupabaseServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { data } = await supabase
    .from("staff_users")
    .select("*")
    .eq("user_id", user ? user.id : "")
    .single();

  if (data && data.staff_role !== "ADMIN" && data.staff_role !== "WRITER") {
    await supabase.auth.signOut();
    redirect("/");
  }

  return (
    <html lang="en">
      <Provider>
        <body
          className={cn(
            ggSans.className,
            "flex flex-col min-h-screen items-center justify-start bg-primary-bg tracking-wide text-white max-h-screen"
          )}
        >
          <Header user={user} />
          {user ? (
            children
          ) : (
            <div className="flex flex-row grow w-full items-center justify-center">
              Not logged in
            </div>
          )}
        </body>
      </Provider>
    </html>
  );
}
